### ISSUE TITLE
Impossible to call yield inside a forEach?

### ISSUE THREAD

**Issue by paglias** [tj/co#148]
If I try to use yield inside a forEach loop (arr.forEach) I get an `Unexpected identifier` error, is this normal? Whatever I try to yield it fails

**Comment by linslin** [comment]
You can use the forEach co lib: https://github.com/juliangruber/co-each

**Comment by Kiranbs890** [comment]
It better to use for loop instead of for each in yield. Since yield behaves like async await which also doesn't work in for each loops.
Use like this 
for ( var a of array){
yield call (functionname,datafromarray)
}
