### ISSUE TITLE
Generator function arguments

### ISSUE THREAD

**Issue by rainder** [tj/co#156]
Is there a way of passing arguments AND context directly into generator function using co? This is what I wanna achieve:

``` javascript
var ctx = {};

var asyncFunction = function *(arg1) {
  expect(this).to.equal(ctx);
  expect(arg1).to.equal('hello');
  return true;
};

co(function*() {
  var b = yield asyncFunction.bind(ctx, 'hello');
  expect(b).to.equal(true);
})();
```

**Comment by bucaran** [comment]
@jonathanong I can't seem to make this work _via_ `co` as in the two examples you wrote above. I looked into `tests/` but could not find tests that test this.

**Comment by bucaran** [comment]
I can't find tests for this and I am unable to make the first example you wrote above work.

```js
co(asyncFunction).call(ctx, 'hello');
```

**Comment by bucaran** [comment]
`co` returns a promise, so maybe you and the OP are trying to do is something else?

```js
co.call(ctx, asyncFunction)
```

will execute the generator and correctly assign `ctx` to whatever `this` is bound to, but there is no way to pass any arguments to the generator function when __the iterator is created__ inside `co` `gen = gen.call(ctx)`.

Sure, yielded values are correctly channeled, but what I would like to have is the ability to pass arguments into the generator function when it is firstly created like this:

```js
co.call(ctx, gen, ...values)
```

I have submitted a simple PR addressing this simple issue.
