### ISSUE TITLE
question: how to async with co

### ISSUE THREAD

**Issue by yoshuawuyts** [tj/co#157]
Sometimes generators confuse _the soul out of my body_ and I definitely don't want to be above asking help, so here goes:

How do you `yield` in co, within a callback without having the call stack unwrap itself. Also: how do you yield from a callback; passing in a `generatorFunction` directly stuff breaks. 

This is the function I'm trying to make work:

``` js
function *xhrmw(next) {
  if (!this.url) return yield next;

  var opts = {
    url: this.url + qs.stringify(this.query),
    body: this.body,
    method: this.method,
    headers: this.headers
  };

  xhr(opts, function(err, res, body) {
    if (err) this.throw(err);
    this.response = res;
    this.body = body;
    // <needs a yield, cannot yield, because not a generator function>
  }.bind(this));
}
```

**Comment by arxpoetica** [comment]
@Raynos I've looked for documentation about this nature of `.bind()`_thunk_-like behavior, and can't find it—you're definitely right, it works that way—but I'd like to understand the internals a little better. Can you (or anyone) point me in the right direction?
