### ISSUE TITLE
co eats thrown exceptions

### ISSUE THREAD

**Issue by sqreept** [tj/co#174]
var co = require('co');

co.wrap(function*(){
    throw new Error('Eaten by co exception...');
})()
.then(function(result){
    console.log(result);
})
.catch(function(err){
    throw err;
});

doesn't display anything.

**Comment by MatthewMueller** [comment]
Confused about this as well. Is there anyway to throw an uncaught exception anymore?

**Comment by urbanappetite** [comment]
I ended up replacing the Promise library as described above...now the errors get logged but still not thrown. Also tried the catch addition but that didn't help particularly - and the  multiple catches in case there was some weirdness with using co's within co'a in large call

**Comment by jonathanong** [comment]
why do you actually want to throw uncaught exceptions? either way, that's a promise issue, not a co issue.
