### ISSUE TITLE
Remove bluebird dependency

### ISSUE THREAD

**Issue by tracker1** [tj/co#189]
even if only a dev dependency, wouldn't it make sense to just favor the built in Promise for the node/iojs engines that co supports?

**Comment by jonathanong** [comment]
yeah i'll do this when we start using iojs for CI testing

**Comment by mgcrea** [comment]
Bluebird promises are currently superior to the V8 native implementation:

> Just a comment on native promises, They are in ES six however they don't have the superb long stacktrace support that bluebird has. Also, bluebird can do 1 million promises per second while native promises and chrome are much slower at 25,000. That might not matter to most people but it may matter to somebody.

Some more context by bluebird's author [here](https://github.com/angular/angular.js/issues/6697#issuecomment-42771111)

**Comment by andyhu** [comment]
Also, ES6 promise is slower. Check the benchmark here:
https://github.com/petkaantonov/bluebird/tree/master/benchmark

**Comment by tj** [comment]
even if they're faster it's not something to include in core, easy to replace V8's, and it's just a dev dep
