### ISSUE TITLE
Breaks on ES5 environment

### ISSUE THREAD

**Issue by dtinth** [tj/co#192]
I am using co in an ES5 environment (Node v0.10) using 6to5 to transpile code. For performance reasons, I only transpile my source files, not transpiling any file in `node_modules`. This works fine, since I only depend on libraries that's written using ES5 syntax. Commit 48ca4dcfa6b6a7396aef57e8d78928cfffc814bc breaks it by using the ES6-only generator function syntax.

Since this is non-backwards compatible to previous version, a fallback written in ES5 should be provided.

**Comment by jonathanong** [comment]
yeah sorry. it's funny because the PR was for transpiler support as well. i tagged `4.1.0` as latest, so hopefully doing semver will ignore `4.2.0` for the time being. 

recommendations on how to go forward is welcomed.

**Comment by ruimarinho** [comment]
@dtinth can you try with 4.3.1?

**Comment by dtinth** [comment]
co works! Thank you!
