### ISSUE TITLE
Proposal: co functional array stuff

### ISSUE THREAD

**Issue by greim** [tj/co#199]
```js
co.map(array, function*(){
  // same stuff you can do in co
}).then(result => )
```

(etc...)

Thoughts? I know various async functional libs exist, but do any use the same generator/yieldable syntax as co? I also thought about spinning this up as a separate module, but don't want to reinvent the wheel.

**Comment by jonathanong** [comment]
you can just do `yield array.map(function* () {})`

**Comment by greim** [comment]
That seems awesome. I figured I was over-complicating things. Are there similar shortcuts for `filter`, `reduce`, `some`, etc?

```js
var filtered = yield co.filter(array, function*(item, idx){
   // blah...
})
```

**Comment by jonathanong** [comment]
nope. easy enough to do yourself.

**Comment by madbence** [comment]
`map` works out-of-the-box because you map values to generators, if you need complicated stuff, use [co-filter](https://www.npmjs.com/package/co-filter), [co-reduce](https://www.npmjs.com/package/co-reduce), [co-every](https://www.npmjs.com/package/co-every), etc.

**Comment by jonathanong** [comment]
thanks @madbence !

**Comment by greim** [comment]
Thanks @madbence, that's just what I was looking for :)
