### ISSUE TITLE
support iterables

### ISSUE THREAD

**Issue by jonathanong** [tj/co#201]
found out recently that `yield*` now delegates using`val[@@iterator]()`. thus, `co()` can actually support iterables.

https://blog.domenic.me/es6-iterators-generators-and-iterables/

i'm thinking of actual use-cases, but one i can think of is running an array in series:

```js
co([
  fn1(),
  fn2(),
]).then()
```

we would have to:

- check for `@@iterator`
- check for `.throw()` before trying to execute it

**Comment by benjamingr** [comment]
@jonathanong I don't understand what you're suggesting here. Also it's `val[Symbol.iterator]` in case it matters.

**Comment by jonathanong** [comment]
me neither as i thought about it more :P
