### ISSUE TITLE
Timeouts?

### ISSUE THREAD

**Issue by rauschma** [tj/co#206]
How would you do timeouts in co? Would you use a promise-based solution or is there something co-specific (and possibly more elegant)?

**Comment by ruimarinho** [comment]
I would do promise based. You can check out [timeout-then](https://github.com/thenables/timeout-then) for this purpose.

**Comment by rauschma** [comment]
Got it. Thanks!

**Comment by targos** [comment]
It can be combined with `Promise.race` to throw if a task is taking too long.
Something like:

```js
function timeout(interval) {
  return new Promise(function (resolve, reject) {
    setTimeout(reject, interval || 0)
  })
}
var longTask = download('bigfile.zip');
try {
  yield Promise.race([timeout(10000], longTask]);
} catch (e) {
  // error in longTask or timeout
}
```

**Comment by jonathanong** [comment]
:+1:
