### ISSUE TITLE
How should i use co v4 in loops?

### ISSUE THREAD

**Issue by Shumkov** [tj/co#213]
Hello folks,

For previous version of c (v3) we have few solutions on wiki page, but they doesn't work with v4.

I need something like this:
```
array.forEach(function *() {
    yield asyncFunction();
});
```

**Comment by yanickrochon** [comment]
```js
yield array.map(function (item) {
  return function * () {
    yield asyncFunction();
  };
});
```

BTW: this isn't [StackOverflow](http://stackoverflow.com/).

**Comment by Shumkov** [comment]
Thanks. Sorry for that.

**Comment by TEugen** [comment]
Should this be added to the examples? I can PR

**Comment by jonathanong** [comment]
better to do:

```js
yield array.map(function* (item) {
  yield asyncFunction()
})
```

**Comment by jonathanong** [comment]
actually no... just do:

```js
yield array.map(asyncFunction)
```

**Comment by jonathanong** [comment]
yes... example welcomed!

**Comment by jonathanong** [comment]
oh this question is for loops. i would do it this way:

```js
for (let val of arr) {
  yield asyncFunction(val)
}
```
