### ISSUE TITLE
Add a `finally()` method 

### ISSUE THREAD

**Issue by bucaran** [tj/co#218]
I would be so much nicer if I could write something like this:
```js
      this.trigger("start")
      co(this.client[key].bind(this))
        .then((val) => {
          this.trigger("ok", val)
        })
        .catch((err) => {
          this.trigger("err")
        })
        .finally(()=> {
          this.trigger("end")
        })
```

I could do the following, but...

```js

      this.trigger("start")
      co(this.client[key].bind(this))
        .then((val) => {
          this.trigger("ok", val)
          this.trigger("end")
        })
        .catch((err) => {
          this.trigger("err")
          this.trigger("end")
        })
```

**Comment by jonathanong** [comment]
you're going to have to bring this up with TC39. we're just returning promises, and we're not gonna implement our own or anything.

**Comment by bucaran** [comment]
@jonathanong :+1: Makes sense.

**Comment by jonathanong** [comment]
i think @domenic said that he tried to get this into the promise spec, but getting `.catch()` in was hard enough already

**Comment by bucaran** [comment]
I thought this could be useful (I still think so), but in my particular use case I (just) realized that triggering an `end` event does not make much sense as the error means whatever was happening didn't properly `end `, so it should be handled separately.

**Comment by targos** [comment]
This should work as well:

```js
      this.trigger("start")
      co(this.client[key].bind(this))
        .then((val) => {
          this.trigger("ok", val)
        }, (err) => {
          this.trigger("err")
        })
        .then(()=> {
          this.trigger("end")
        })
```

**Comment by bucaran** [comment]
@targos Thanks!
