### ISSUE TITLE
Why promise?

### ISSUE THREAD

**Issue by guileen** [tj/co#222]
I like tj design  `co(fn)(nodeStyleCallback)`,

I don't know why it change to promise mode.

But if you really want a promise mode. Please make another API like `co(fn).callback(callback)`.

**Comment by guileen** [comment]
If you change the API, you should bump the major version number.

**Comment by zensh** [comment]
@guileen You can try https://github.com/thunks/thunks

thunk(fn)(nodeStyleCallback)

**Comment by tj** [comment]
with promises being official it's kinda what we have now like em or not
