### ISSUE TITLE
Executing loops in series?

### ISSUE THREAD

**Issue by overlookmotel** [tj/co#227]
Hello all.

Is there a recommended way to execute a function in a loop in series with co?

For example, this executes a loop in series:

```js
co(function *() {
    var order = [];
    for (var i = 1; i <= 3; i++) {
        order.push('start' + i);
        yield Promise.resolve();
        order.push('end' + i);
    }
    // order = ['start1', 'end1', 'start2', 'end2', 'start3', 'end3']
});
```

But this executes it in parallel:

```js
co(function *() {
    var order = [];
    yield [1, 2, 3].map(co.wrap(function*(i) {
        order.push('start' + i);
        yield Promise.resolve();
        order.push('end' + i);
    }));
    // order = ['start1', 'start2', 'start3', 'end1', 'end2', 'end3']
});
```

Is there any way to get it running serially, perhaps using `yield*`?

Use case is that it'd be great to be able to use any flow control construction (lodash's `_.mapValues()` for example) with co, rather than having to utilise specialised co-compatible flow control libraries.

**Comment by overlookmotel** [comment]
I published an npm module [co-series](https://www.npmjs.com/package/co-series) aiming to solve this problem, but I'm sure there's a better way to do it...

**Comment by cesarandreu** [comment]
I'm not sure what problem you're trying to solve, your example doesn't make sense to me. Whenever I need to do something sequential I use either `Array.prototype.reduce` or I use a recursive function.

With both you can pass `Promise.resolve([])` as the initial value and keep chaining that promise.

**Comment by overlookmotel** [comment]
Sorry, I didn't explain myself well. And maybe I'm fundamentally misunderstanding how generators work.

What I'm trying to say is: the joy of co, generators and `yield` is to be able to write async code in a sync style, using `yield` to say "wait for this to complete".

The natural extension of this, it seems to me, would be to be able to use any sync control flow construction.

So something like this works as expected:

```js
co(function *() {
    var order = [];
    for (var i = 1; i <= 3; i++) {
        order.push('start' + i);
        yield Promise.resolve();
        order.push('end' + i);
    }
    // order = ['start1', 'end1', 'start2', 'end2', 'start3', 'end3']
});
```

The loop executes in sequential order, as if it was sync.

But is there a way to do the same thing with `.map()`?

```js
var order = [];
var fn = function *() {
    order.push('start' + i);
    yield Promise.resolve();
    order.push('end' + i);
    return i * 10;
};

co(function *() {
    var res = yield [1, 2, 3].map(fn);
    // order = ['start1', 'start2', 'start3', 'end1', 'end2', 'end3']
    // res = [10, 20, 30]
});
```

The above executes `fn()` three times, and the yielded result `res` is what you expect. BUT, `fn()` is being run 3 times in parallel, rather than each iteration of the loop running after the last one has completed, sync style.

So I tried using `yield*` to delegate:

```js
co(function *() {
    var res = yield* [1, 2, 3].map(fn);
    // order = ['start1', 'end1', 'start2', 'end2', 'start3', 'end3']
    // res = undefined
});
```

This executes `fn()` 3 times, this time in series. Great! BUT `res = undefined` so you've lost the map result.

Is there a way to have this cake and eat it too?

I'm aware that there are many ways to achieve this, using `.reduce()` and promise-chaining, or `Promise.each()` etc. But my point is that it'd be great if it were possible to avoid specialised promise/co methods and just write code in a sync style, using sync flow control constructions like `.map()` or lodash's `_.mapValues()` for iterating through object keys.

I hope that makes a bit more sense. Any thoughts?

**Comment by madbence** [comment]
`map` is sync, you cannot change that. `yield arr.map(fn)` works, because `co` can deal with arrays, `yield* arr.map(fn)` works because arrays are iterable.

```
function* foo() {
  yield 1;
  yield 2;
  yield 3;
}

function bar() {
  yield* [1, 2, 3];
}
```

Here `foo` and `bar` do essentially the same. `co` has no idea that the 3 values should be grouped together.

**Comment by bucaran** [comment]
@overlookmotel This is possibly related to https://github.com/tj/co/issues/233

Should be closed.

**Comment by 7flash** [comment]
```
function* foo() {
  yield 1;
  yield 2;
  yield 3;
}

function bar() {
  yield* [1, 2, 3];
}
```

How to use these examples in the same way?
