### ISSUE TITLE
use bluebird?

### ISSUE THREAD

**Issue by tunnckoCore** [tj/co#228]
To be backward compatible to node 0.10?

**Comment by tj** [comment]
0.10 doesn't have generators (without that hacky / super slow transpiler at least)

**Comment by madbence** [comment]
Afaik `co` works just fine with `babel` (or other transpilers).

**Comment by tunnckoCore** [comment]
oh yea yea, i forgot or we can run with `gnode` yep.

**Comment by cheshirecatalyst** [comment]
I'm not one to cry performance very often, but the performance in execution time and memory of bluebird is significantly better than native promises. I can understand the reluctance to involve a dependency for promises, however as co is used in koa and a large portion of supporting modules, won't the use of natives have a large impact on my koa application's footprint?

**Comment by tj** [comment]
Can't bluebird be used as a polyfill of sorts? (external to co). Either way I would say this would be negligible in most cases, even if numbers are vastly different it's a rain drop in an ocean in terms of over-all app performance. Koa with native promises still does an easy 6k+ rps, which is quickly reduced to say 1k as soon as you do anything "real". I'd suggest measuring first and see if it'll mean much for your app, but I also think you can just use it as a polyfill (might be wrong)

**Comment by cheshirecatalyst** [comment]
I'm not sure about using it as a polyfill in such a way as to prevent co (and thus all the modules utilizing it) from using native Promises at their core, any suggestions?
 
As far as meaning much to my app. I'm almost certain it would. Having messed around with various async solutions (including co) to various db's and other async tasks in express4 with several "real" applications, it (bluebird) has shown to be the least harmful to the footprint.

I ported some heavy parts of an existing api to koa in the interest of embracing the new awesome. To find that my 1.2k-ish  rps in express4 had dropped to 300 in koa with a memory footprint that was unacceptable during load.

So I examined the codebase of koa, and arrived here at co. Everything else seemed pretty sane, just as I would expect from such awesome people. 

Overall It's no big deal, i'll just wait around and see if native promises ever catch up, I was just sad that I couldn't use koa for something other than playing around, and figured non natives here might drain the ocean a bit.

Or maybe I just suck at using koa or programming. (probably the latter ^_^)

**Comment by tj** [comment]
If I remember I'll see if someone on the team can try it with our app. I'm not a huge fan of random promise implementations being spread throughout libraries, when it's more of a polyfill type of concern, but we'll see

**Comment by mjhm** [comment]
FWIW Our group has just started converting Promise patterns to generator patterns, but we're stuck with some "least bad" choices because we depend on added bluebird functionality (such as using error predicate functions in `.catch` callbacks).

It would be ever so convenient for us if `co` allowed for an optional dependency injection for the Promise library.
