### ISSUE TITLE
How to yield a list of generators inside another generator?

### ISSUE THREAD

**Issue by bucaran** [tj/co#233]
I have a list of generators and I want to yield each in a series inside `co( )` like this:

```js
co(function* () { 
  /* for each in generator list
  do something
  yield generator
  do something else
  */
})
```

Currently I am using a `for of` loop, but is there a way to accomplish this without mutation?

**Comment by cesarandreu** [comment]
Recursion :D.

```js
var performTasks = co.wrap(function * performTasks (arr) {
  var task = arr.shift()
  if (task) yield task
  if (arr.length) yield performTasks(arr)
})

co(function * () {
  yield performTasks([fn1, fn2, ...])
})
```

(Actually, since co lets you yield generators, you could avoid the extra co.wrap I think.)

**Comment by bucaran** [comment]
I mean, yes, I tried recursion, and even a strange recursive generator, but now you tell me wrap was the key to this!! :laugh:

Thanks.
