### ISSUE TITLE
DefinitelyTyped

### ISSUE THREAD

**Issue by lnlwd** [tj/co#234]
Hello guys!!
I need to use CO with TypeScript, but i can't find the definitions...

Can you make a definition file and push to the DefinitelyTyped repository??

https://github.com/borisyankov/DefinitelyTyped

Thanks! :smile:

**Comment by tracker1** [comment]
@lnlwd AFAIK TypeScript doesn't as of yet support Generators, which is really a prerequisite for this type of functionality as it stands.

**Comment by lnlwd** [comment]
Ok, I understand!

**Comment by bucaran** [comment]
Close.

**Comment by TimMensch** [comment]
TypeScript supports generators now. Please reopen and add type declarations?
