### ISSUE TITLE
Node version support

### ISSUE THREAD

**Issue by bucaran** [tj/co#236]
From → flyjs/fly/issues/56

`co` can work with as little as `0.11`, however `package.json` is just listing

```json
  "engines": {
    "iojs": ">= 1.0.0",
    "node": ">= 0.12.0"
  }
```

Is there any reason for this that I may have missed?

**Comment by ruimarinho** [comment]
@bucaran I think it is purely a decision from a [maintainer perspective](https://github.com/tj/co/commit/2203ee50656b2bba16f72ecce531baf346f75dd2), i.e. not having to check yet another version which isn't widely adopted. This requirement is not strict so npm will still install `co` with a warning but the package works fine with node 0.11 even if not "officially sanctioned".

**Comment by bucaran** [comment]
@ruimarinho Thanks! Makes sense to me.
