### ISSUE TITLE
expose toPromise

### ISSUE THREAD

**Issue by joshrtay** [tj/co#251]
It would be useful if `toPromise` was exposed on `co`. Would guys accept a pull request for this?

**Comment by alsotang** [comment]
it's a convenience method yes. though co doesn't do this. we can just copy the code, and publish a `to-promise` package on npm.

**Comment by joshrtay** [comment]
you would have to copy nearly half of co which doesn't seem ideal. i created a hacky version of `to-promise` [here](https://github.com/joshrtay/to-promise). it looks like:

```js
function toPromise (v) {
  return co(function * () {
    return yield v
  })
}
```

i think it would still be nice to expose `toPromise` or move a bunch of those helper methods into their own repos.

**Comment by alsotang** [comment]
why not just import co, and do  `co(genOrOthering).then()`?
is some scenes that `to-promise` can handle, but co dont?

2015-11-15 12:01 GMT+08:00 Josh Taylor <notifications@github.com>:

**Comment by joshrtay** [comment]
`co(otherThing)` will just `resolve(otherThing)`. I want:

```js
function toPromise(obj) {
  if (!obj) return obj;
  if (isPromise(obj)) return obj;
  if (isGeneratorFunction(obj) || isGenerator(obj)) return co.call(this, obj);
  if ('function' == typeof obj) return thunkToPromise.call(this, obj);
  if (Array.isArray(obj)) return arrayToPromise.call(this, obj);
  if (isObject(obj)) return objectToPromise.call(this, obj);
  return obj;
}
```

**Comment by yanickrochon** [comment]
@joshrtay  If `obj` is a number or string, it will just return it, which is not a promise. Shouldn't it be

```
function toPromise(obj) {
  if (!obj) return obj;
  if (isPromise(obj)) return obj;
  if (isGeneratorFunction(obj) || isGenerator(obj)) return co.call(this, obj);
  if ('function' == typeof obj) return thunkToPromise.call(this, obj);
  if (Array.isArray(obj)) return arrayToPromise.call(this, obj);
  if (isObject(obj)) return objectToPromise.call(this, obj);
  return Promise.resolve(obj);
}
```

?

**Comment by joshrtay** [comment]
@yanickrochon That would definitely be better. That's just a copy of the code from `co`.

**Comment by tj** [comment]
separate module makes more sense than exposing to me

**Comment by tj** [comment]
closing for now, but a PR to use the new module would be :+1: with me

**Comment by joshrtay** [comment]
cool. will do.

**Comment by yanickrochon** [comment]
Well, someone might as well take the [promisify](https://www.npmjs.com/package/promisify) project (or any other project of the like) and recycle it. It's about time we stop creating duplicates for every damn features.

**Comment by yanickrochon** [comment]
Then again [promisify-any](https://www.npmjs.com/package/promisify-any) seems to be doing *exactly* what you want with no need to change anything with `co`... The only downside is the `bluebird` requirement.

**Comment by joshrtay** [comment]
Haden't seen that before. Thanks.

That's a pretty big downside. `bluebird` is unnecessarily big.
