### ISSUE TITLE
Api: export toPromise, arrayToPromise, objectToPromise functions

### ISSUE THREAD

**Issue by epoberezkin** [tj/co#261]
`co.toPromise` etc.

They are quite useful utility functions.

@tj is it ok?

**Comment by tj** [comment]
nahh if anything they should be in npm otherwise that's a weird unrelated public api for co

**Comment by epoberezkin** [comment]
ok, no problem :)

**Comment by epoberezkin** [comment]
copy-paste is ok too ;)
Could you please tell me why this:

```
// predefine the key in the result
results[key] = undefined;
```

is needed [in objectToPromise](https://github.com/tj/co/blob/master/index.js#L181)?
Thank you very much!
