### ISSUE TITLE
simple version

### ISSUE THREAD

**Issue by cauburtin** [tj/co#263]
I've seen simple versions of  coroutines (sorry not 'cogenerators'), like http://jsbin.com/jelaku/3/edit?html,js,console

what does this module do more ?

**Comment by tj** [comment]
Sorry? It does what's mentioned in the Readme

**Comment by freiit** [comment]
Check the source. 
Deals with all corner cases, throws and catches always as expected, deals with arrays and other structures and is as close as possible to the ES7 async/await standard.

**Comment by cauburtin** [comment]
Ok thanks, I'm trying to learn about yield

for normal arrays, isn't it just wrapping in Promise.all? but ok for other corner cases

**Comment by tj** [comment]
@cauburtin there are some features to yield `[]` and `{}`, but I would personally ignore those since they're not future-proof with async/await. I'd stick to Promise.all() etc, that way later you can replace `co` with async/await when it's natively supported by node
