### ISSUE TITLE
yield promise array did not get result

### ISSUE THREAD

**Issue by stableShip** [tj/co#266]
testing co yield array
```
var Promise = require("bluebird")
var co = require("co");
var fs = require("fs");
var parallel = require('co-parallel');
fs = Promise.promisifyAll(fs);
co(function* () {
    var promise = fs.readFileAsync("./test.js")
        .then(function () {
            return 1
        })
    var promises = [];
    for(var i=0;i<100000;i++){
        promises.push(promise);
    }
    var start = new Date().getTime();
    var res = yield promises
    console.log(res,res.length,new Date().getTime()- start);
});
```
can not get result of `yield promises` 
but use `co-parallel` `parallel(promises) ` get the result . 
very confuse.  I have no idea what's error?

**Comment by freiit** [comment]
Take everything away that is not co and it works:

var co = require("co");
co(function* () {
 var promise = new Promise(res => setTimeout(res, 200))
 var promises = [];
 for(var i=0;i<100000;i++){
  promises.push(promise);
 }
 var start = new Date().getTime();
 var res = yield promises
 console.log(res,res.length,new Date().getTime()- start);
}).


Issue must be somewhere in bluebird?

\Christoph

**Comment by stableShip** [comment]
yes it work,and console.log a lot of `undefined`, I change a little bit, it didn't work again

use native Promise Library in node-v4.4.1 with follow code,still not get the result
```
co(function* () {
    var promise = new Promise(function(res){
        setTimeout(function(){
            Promise.resolve(1);
        },200)
    })
    var promises = [];
    for(var i=0;i<100000;i++){
        promises.push(promise);
    }
    var start = new Date().getTime();
    console.log(promises.length);
    var res = yield promises
    console.log(res,res.length,new Date().getTime()- start);
});
```

**Comment by freiit** [comment]
I think you confused yourself now. ;)

Don't call 'Promise.resolve(1)' (creates a new promise), just call 'res(1)'

\C

**Comment by stableShip** [comment]
oh,get it, it work. res -> resolve, i am a fool
