### ISSUE TITLE
Support  yielding Task types (e.g. data.task)

### ISSUE THREAD

**Issue by tb01923** [tj/co#270]
I find myself working with folktale, ramda, and the other related libraries.  It would be cool if co could support yielding on Task types.  The change seems simple (but I am a bit simplistic, so perhaps I missed something): 

A couple of helpers

```Javascript
function taskToPromise(a) {
  return new Promise(function(resolve, reject) {
    a.fork(reject, resolve)
  })
}

function isTask(obj) {
  return 'function' == typeof obj.fork;
}
```
and then a modification of toPromise:

```Javascript
function toPromise(obj) {
  if (!obj) return obj;
  if (isPromise(obj)) return obj;
  if (isGeneratorFunction(obj) || isGenerator(obj)) return co.call(this, obj);
  // this seems like a good place to stick this
  if (isTask(obj)) return taskToPromise.call(this, obj);
  if ('function' == typeof obj) return thunkToPromise.call(this, obj);
  if (Array.isArray(obj)) return arrayToPromise.call(this, obj);
  if (isObject(obj)) return objectToPromise.call(this, obj);
  return obj;
}
```

Putting it into action, to test above.  First a couple of helpers random num generators, and then task factory that retunrs a Task that resolves some computation within a random 3 seconds:

```Javascript
const random = () => (Math.floor(Math.random() * 10000) + 999)
const timeout = () => (Math.floor(Math.random() * 3000) + 100)

// makeTask :: (boolean, (a->b)) -> Task
const makeTask = (bool, computation) => new Task((reject, resolve) => {
    const x = computation()
    const t = timeout()
    setTimeout(() => {
        if (bool) {
            resolve({"success": x});
        } else {
            reject({"failed": x});
        }
    }, t)
})
```

And then create the test and kick it off

```Javascript
const test = function*() {
    const x = yield makeTask(success, random)
    return x
}

co(test).then(console.log, console.error)
```

I understand every library can't support everything, but this would make it is easier to integrate the Task type with the legacy code I have in place.  Always happy to learn, so if this is a bad idea I would love insight why.

Thanks

**Comment by LeonineKing1199** [comment]
Tasks are flawed in the same way that Promises are in the sense that they don't share state among multiple asynchronous calls so I've seen pretty, um, interesting approaches to handling that (pumping arrays up full of various params).

Generator-based control flow like co() solves this rather elegantly.

if anything, co() + Maybe should give you the same flow you seek but folktale's Maybe has kind of an ugly interface.

**Comment by tj** [comment]
co already does too much stuff sorry! people should be preparing for async/await, which does not support the same things. 

cheers

**Comment by gunar** [comment]
[I did it thought :weight_lifting_man:](https://github.com/gunar/co). I think of it more as a coding exercise really.
