### ISSUE TITLE
Could we export toPromise?

### ISSUE THREAD

**Issue by gunar** [tj/co#272]
I'd like to use `co` but I'm not sure I can. I'm currently using generators, but not coroutines.

What's the deal? I have generators that return strings. Eventually, my generators need to do some async stuff (db calls) before outputting those strings.

Currently I'm doing something very similar to `co`. That is, if the generator output `value` is a Promise, I chain it a `then` that passes the value back in. However, if the output is a string, I use it for other purposes.

e.g.

```js
function *myGenerator(input) {
  let step
  const remoteVersion = yield 'Version: 0.0.1'
  const remoteVersionFound = yield find(remoteVersion) // <- find returns a promise
  if (remoteVersionFound !== undefined) = step yield 'Files: a, b, c'
  else step = yield 'Not found'
  // do stuff with "step"
  return 'End'
}

const instance = myGenerator()
instance.next()
const step = instance.next('Version: 0.0.2')
// do stuff with "step"
/// ...
```

So, I'd like to rely on the community-built functions from `co` (e.g. `toPromise`). For that, I'd need `co` to export it.

OR, could I use `co` in this situation?

Thanks a bunch!

**Comment by LeonineKing1199** [comment]
Co returns a Promise itself that resolves to the 'done' value of your generator, in your case the value of the boolean expression you return at the end.

So you just need:
```
co(myGenerator).then(booleanValue => { /* ... */ });
```

Am I understanding you correctly?

**Comment by gunar** [comment]
I didn't make myself clear there. Sorry.

I need the intermediate yielded values too, not just the final value. I've updated my example to try and make it more clear.

So what I need is:

1. When I yield a Promise (or anything async for that matter), I want it to be resolved and `next()`ed back into the generator
2. When I yield something else (strings, integers,...) I want to have access to that, for further computing

Can that be done with `co`?

Thank you!

**Comment by LeonineKing1199** [comment]
Unless TJ wants to correct me, I don't think `co` will give you what you want. The beauty of `co` is that you don't have to call `.next()` repeatedly. You seem to actually want that and asuch, I don't think `co` is the tool for that job.

`co` was more or less made for pure asynchronous control flow where you're never really calling the iterator directly. Instead, `co` takes whatever you give it and then it hooks back into your generator with whatever it did with what you gave it (resolving promises, executing thunks).

**Comment by gunar** [comment]
Yes you do. Agreed. I want to have access to some yielded values, and that doesn't match `co`s intent.

Still, I could use 80% of `co` (mostly `toPromise` and derivative fns). Is there any possibility of exporting that? :)

**Comment by tj** [comment]
Those things are just implementation details, but feel free to copy/paste them into your own npm module(s). They shouldn't be exported though since that changes the public api

**Comment by gunar** [comment]
Fair enough. Thank you @LeonineKing1199 and thanks @tj.

Have a good one!

**Comment by zensh** [comment]
@gunar https://github.com/thunks/thunks is what you need.

**Comment by gunar** [comment]
@zensh Thanks for the suggestion. I've investigated `thunks` but can't see how it can solve my problem. Thanks anyway.
