### ISSUE TITLE
Switching to async functions

### ISSUE THREAD

**Issue by electerious** [tj/co#275]
`co` seems to be the perfect solution while waiting for native async functions. Is my assumption correct that (1) can be easily changed to (2) without any trouble as soon as async functions are widely supported?

```js
// 1

var fn = co.wrap(function* (val) {
  return yield Promise.resolve(val);
});

fn(true).then(function (val) {

});

// 2

var fn = async function (val) {
  return await Promise.resolve(val);
};

fn(true).then(function (val) {

});
```

Are there're other problems I could run into when switching?*

(*) I'm aware of the fact that `co` allows several yieldable objects, while async functions only allow to await promises.

**Comment by gunar** [comment]
As far as I understand, async functions always return a Promise so (2) could be simplified as:
```js
// 2

var fn = async function (val) {
  return val;
};

fn(true).then(function (val) {
  assert.equal(val, true);
});
```

**Comment by electerious** [comment]
True. `return await Promise.resolve(val);` is senseless as it waits for the Promise to be resolved and then just returns the value which is the same as using `return val;` directly.

This should also work and do the same:

```js
// 2

var fn = async function (val) {
  return Promise.resolve(val);
};

fn(true).then(function (val) {

});
```

**Comment by gunar** [comment]
As I said, I don't think you even need to `Promise.resolve`, bro.

**Comment by fritx** [comment]
Is there any library that converts `async/await` to `co.wrap`? Just like [babel-preset-async-to-bluebird](https://github.com/eknkc/babel-preset-async-to-bluebird).

My current environment supports generators, so I want to drop the `regenerator` runtime included at babel-plugin-transform-runtime

```js
var fn = async () => {
  return await Promise.all([1, 2])
}

// into
var fn = co.wrap(function *() {
  return yield [1, 2]
})
```

**Comment by gunar** [comment]
@fritx I've been thinking about writing a jscodeshift transform for that! Actually, for the other way around, so I may remove `co` as soon as async/await lands on Node.js. Either way, it is doable and should be fun.

**Comment by fritx** [comment]
Cool. Let me know then. @gunar

**Comment by loganfsmyth** [comment]
@fritx Since you pinged this in Babel's support chat, if you look at the implementation of that preset: https://github.com/eknkc/babel-preset-async-to-bluebird/blob/master/index.js#L3

so you can also do

```
  "plugins": [
    [require('babel-plugin-transform-async-to-module-method'), {
      module: 'co',
      method: 'wrap'
    }]
  ]
```

to do this already.

**Comment by gunar** [comment]
@loganfsmyth Cool! Do you think we could use that to actually edit the files? Thanks!

**Comment by loganfsmyth** [comment]
The main issue is that at the moment Babel makes no effort to preserve original code formatting, so Babel's transforms are better for continued transformation rather than one-time conversion.  (Assuming I understand what you're asking.

**Comment by LinusU** [comment]
A bit late to the party, but I have used this package which works awesome: https://github.com/albinekb/co-to-async
