### ISSUE TITLE
Why yield a number is not work in co？

### ISSUE THREAD

**Issue by daleoooo** [tj/co#278]
```
co(function* () {
  yield 1;
  conosle.log('finished');
})
```
The code above is not support in co.
`console.log` would never be reached.
I think this is not reasonable, because generator function support the code above.

Thank you for your comments.

**Comment by gunar** [comment]
The yieldable objects currently supported are:
- promises
- thunks (functions)
- array (parallel execution)
- objects (parallel execution)
- generators (delegation)
- generator functions (delegation)

`co` simply "doesn't know" what to do with a number.

**Comment by JWo1F** [comment]
@gunar `co` may just send unknown type to `.next` :)

**Comment by gunar** [comment]
@JWo1F why would we want that?

**Comment by daleoooo** [comment]
@gunar Thank you for your comment. I know what kind of objects are yieldable in co, and I know the goal of co. What I mean is that co may cover the code above, or throw error like @JWo1F  said, instead of stop without any warning.

**Comment by gunar** [comment]
@daleoooo well I do get an error...
```
Promise {
  <rejected> TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "1"
...
```

**Comment by dead-horse** [comment]
@daleoooo co return a promise, and you must catch it.

```js
co(function* () {
  yield 1;
  conosle.log('finished');
}).catch(err => console.error(err.stack));
```

**Comment by daleoooo** [comment]
@dead-horse @gunar Thank you. It works and catching error is important. I miss it.

**Comment by gunar** [comment]
@daleoooo happy to help. please close the issue if you think it's solved. thanks!
