### ISSUE TITLE
'yield generator' blocks  running of the code after it

### ISSUE THREAD

**Issue by nanda221** [tj/co#287]
the code is very simple.

function* aa() {
  console.log(1);
  yield function* (){
    yield 1;
  };
  console.log(2);
}

co(aa);

but, the 'console.log(2)' doesn't execute.

anyone who ever used yield generator or generator functions like me, please help me, thanks.

**Comment by tj** [comment]
Co expects the values you yield (1 in this case) to be a Promise, function, or another generator etc.

**Comment by nanda221** [comment]
Thanks for your answer,tj. things I ready want is a pipe like koa. here is my code.
```
function* aa(next) {
  console.log(1);
  yield next;
  console.log(2);
}

function* bb(next) {
  console.log(11);
  yield next;
  console.log(22);
}

var arr = [aa, bb];

function pipe(){
  let plugin = arr.shift();
  if(plugin) {
    return co.wrap(function * (){
      yield plugin(pipe());
    });
  }
  return Promise.resolve(true);
}

pipe()();
//"1"
//"11"
//"22"
//"2" is missed.
```
is there something I did wrong, or you have a better implementation for this case. thanks again.

**Comment by tj** [comment]
Might not be exactly what you want but I personally use channels for stream-like producer/consumer situations https://github.com/tj/channel.js, and pass around the channel. https://github.com/tj/channel.js/blob/master/examples/http.js is a bit of a contrived example but hey!

**Comment by nanda221** [comment]
thanks, tj, I'll check this.
