### ISSUE TITLE
Loosing parameters passed from co-wrapped function to another one

### ISSUE THREAD

**Issue by dj-hedgehog** [tj/co#288]
I'm using the latest co-module (4.6). 

This is a Koa-middleware. Therefore it is already `co()` wrapped.

```
  create: function * () {
    try {
      this.body = yield services.createIt({obj: true})
    } catch (err) {
      this.body = { "errors": err.details }
      this.status = err.status
    }
  }
```

It is calling another generator-function I'm manually wrapping with `co`:

```
  const co = require('co')

  createIt: co(function * (obj) {
    console.log(obj) // --> undefined
  }
```

Why do I "loose" the parameter?

**Comment by nhim175** [comment]
@dj-hedgehog have you tried this?
```
createIt: co.wrap(function* (object) {
```

**Comment by crunchtime-ali** [comment]
Yeah that is what I ultimately ended up doing.
In the meantime I could switch all my projects to native async..await for instances where I required this behaviour.
