### ISSUE TITLE
Does not work with node v6.5

### ISSUE THREAD

**Issue by bishtawi** [tj/co#292]
Recently updated node to the latest v6.5 and my webapp fails with this stack trace:
```
TypeError: Cannot read property 'done' of undefined
      at next (/Users/dev/work/node_modules/co/index.js:98:14)
      at onFulfilled (/Users/dev/work/node_modules/co/index.js:69:7)
      at /Users/Stephen/dev/work/node_modules/co/index.js:54:5
      at Object.co (/Users/dev/work/node_modules/co/index.js:50:10)
      at next (/Users/dev/work/node_modules/co/index.js:99:29)
      at onFulfilled (/Users/dev/work/node_modules/co/index.js:69:7)
```
I am not sure if the source of the issue is really co or some other library as the stack trace does not extend past co. I am using the [koa](https://github.com/koajs/koa) framework, if that matters.
Code worked fine with node v6.4.

**Comment by bishtawi** [comment]
Ok, I started stripping out third party libs, middleware and large pieces of the app to see when the error would go away. I narrowed it down to [koa-generic-session](https://github.com/koajs/generic-session) or [koa-convert](https://github.com/koajs/convert). Its most likely not a co issue.

**Comment by bishtawi** [comment]
We can probably close this issue.

**Comment by targos** [comment]
@bishtawi It's still worrying that something broke between Node.js v6.4 and v6.5. Can you please mention me if you find where the issue is ?

**Comment by ahan** [comment]
I got the same issue, at last, I found that it is the '--harmony' args cause the 'Cannot read property 'done' of undefined'

From old time, my deploy script was try to start the nodejs application with 'node --harmony path/to/app.js'

Now I remove the 'harmony' args, issue solved.

**Comment by bishtawi** [comment]
Yup, I [eventually](https://github.com/koajs/convert/issues/6) narrowed it down to the harmony flag as well.

**Comment by kothari775** [comment]
I am facing same issue with node v6.9. please share if anyone knows solution.

**Comment by bishtawi** [comment]
@kothari775 Run node without the `--harmony` flag. You shouldnt be using it anymore.

**Comment by kothari775** [comment]
@bishtawi Thanks a lot.
