### ISSUE TITLE
Set a sleep interval between each resolve?

### ISSUE THREAD

**Issue by elgs** [tj/co#311]
```javascript
co(function *(){
  // resolve multiple promises in parallel 
  var a = httpRequest(...);
  var b = httpRequest(...);
  var c = httpRequest(...);
  var res = yield [a, b, c];
  console.log(res);
}).catch(onerror);
```

Is there a way for me to introduce a second of sleep between each http request? Thanks.

**Comment by ifsnow** [comment]
Is this what you want?

```js
function sleep(ms) {
  return new Promise(function (resolve, reject) {
      setTimeout(resolve, ms);
  });
}

co(function *(){
  var a = yield httpRequest(...);
  yield sleep(1000);
  
  var b = yield httpRequest(...);
  yield sleep(1000);
  
  var c = yield httpRequest(...);  
  yield sleep(1000);  
}).catch(onerror);
```

**Comment by freiit** [comment]
var sleep = ms => new Promise(res => setTimeout(res, ms))
    co(function *(){
      // resolve multiple promises in parallel 
      var a = httpRequest(...);
      yield sleep(1000);
      var b = httpRequest(...);
      yield sleep(1000);
      var c = httpRequest(...);
      var res = yield [a, b, c];
      console.log(res);
    }).catch(onerror);

**Comment by elgs** [comment]
Thanks @ifsnow. Your code works for me!
