### ISSUE TITLE
.catch and .then are both called when an exception is thrown

### ISSUE THREAD

**Issue by kevinbror** [tj/co#323]
Given a snippet like the following both catch and then are called which is incorrect. 
```
const Co = require('co');
Co(function* () {
  throw new Error('oops');
}).catch((err) => {
  console.log(`catch got called: ${err.message}`);
}).then(() => {
  console.log('then got called too');
});
```

This case however works as expected
```
const Co = require('co');
Co(function* () {
  throw new Error('oops');
}).then(() => {
  console.log('not me');
}, (err) => {
  console.log(`only I got called: ${err.message}`);
});
```

I'm using the latest version.

**Comment by freiit** [comment]
Works as intended. "Catch" returns a promise. And if you don't throw in a
"catch", the promise gets resolved.

See also here for examples:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

**Comment by kevinbror** [comment]
Got it. Thanks for clarifying!
