### ISSUE TITLE
How to wrapper a event style module to use with co.

### ISSUE THREAD

**Issue by Pana** [tj/co#82]
We can change a function with callback through thunkify. How does we use a event style module with co ? Promise ?

**Comment by gunar** [comment]
Is this still the recommended solution? I'm be afraid to use it because of this:
> Thunk support only remains for backwards compatibility and may be removed in future versions of co.

**Comment by tj** [comment]
@gunar generally recommended to use async/await now if you can, co was/is mostly just a stop-gap, but I think for that reason co will remain as-is for the most part.

**Comment by gunar** [comment]
@tj thanks! what do you recommend if I'm on Node? `co` is super useful already, are there even better alternatives? [asyncawait](//github.com/yortus/asyncawait) looks nice too.

**Comment by freiit** [comment]
@gunar Currently `async / await` functions are on stage 3: [https://tc39.github.io/ecmascript-asyncawait/](https://tc39.github.io/ecmascript-asyncawait/). So if you like `babel`, use it with this config: ` { "presets": ["es2016", "stage-3"] }` and you can use (hopefully) the new syntax already. Should work without change when draft is finalized/node catches up.

**Comment by yosbelms** [comment]
> co was/is mostly just a stop-gap
@gunar @Pana you may want to check [this](yosbelms/getjs) out. `Getjs` is control flow library akin to `co` plus CSP (channels like Golang and Clojure), it integrates very well with `Node.js` async API.
