### ISSUE TITLE
Unexpected token *

### ISSUE THREAD

**Issue by sbarow** [tj/co#9]
Trying to run the examples but I keep getting and "Unexpected token *" error for "co(function *(){"

Please advise if there is something special that I need to do to get this to run.

**Comment by xueenda** [comment]
I have the same issue.
node version is v0.12.0
Should be a problem I have no idea why.

**Comment by tracker1** [comment]
@sbarow 0.12.x should work too, as should any version of io.js ...

You may also want to look into BabelJS

**Comment by sbarow** [comment]
Thanks @tracker1 I posted this 2 years ago, have since learnt about the harmony flag ;-)

For anyone stumbling onto this post to start node with the harmony flag:

`node --harmony index.js` and `co` should work.

**Comment by bucaran** [comment]
@sbarow Hi. I suppose you have been using co for a while now. What are some of the most interesting things you have discovered you can do with it? 

Regards
